version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: polybase-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: polyroot
      MYSQL_DATABASE: Relation
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polybase-api
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_USER: root
      DB_PASSWORD: polyroot
      DB_HOST: mysql
      DB_PORT: 3307
      DB_NAME: Relation

volumes:
  mysql_data:
